name: Ruff
on: pull_request
jobs:
  lint:
    name: Lint, Format, and Commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        name: Lint
        with:
          version: 0.3.5
          args: "check --output-format=full --statistics"
      - uses: chartboost/ruff-action@v1
        name: Format
        with:
          version: 0.3.5
          args: "format --check"
